services:
  webapp:
    container_name: rwt
    build:
      context: ./setup/rwt-apache-php-8.3
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    ports:
      - "7000:80"
      - "5200:5173"
    volumes:
      - ./laravel:/var/www/html:cached
      - ./setup/config/php.ini:/usr/local/etc/php/conf.d/99-local.ini
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    networks:
      - app-network

  database:
      container_name: mysql8-rwt
      restart: always
      image: mysql:8
      volumes:
        - db:/var/lib/mysql
      ports:
        - "3300:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: rwt
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
  vendor:
  node_modules:
